[package]
name = "afmt-web-service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
serde = { version = "1.0.217", features = ["derive"] }
tempfile = "3.17.1"
tokio = { version = "1.43.0", features = ["full"] }
hyper = { version = "0.14", features = ["server"] }
