services:
  - type: web
    name: afmt-web-service
    runtime: rust
    buildCommand: |
      chmod +x afmt
      cargo build --release
    startCommand: ./target/release/afmt-web-service
    env: rust
    envVars:
      - key: PORT
        value: 10000
    port: 10000
